spring.application.name: core-application
spring.profiles.active: local

spring:
  config:
    import:
      - logging.yml
      - db-core.yml
  web.resources.add-mappings: false


server:
  tomcat:
    max-connections: 20000
    threads:
      max: 600
      min-spare: 100

---

